import type { Metadata } from "next";
import "./globals.css";
import { Poppins, Quantico } from "next/font/google";
import { ToastProvider } from "./components/ToastProvider";

const quantico = Quantico({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-heading",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "Muhammed Oroye — The Oroye Campaign",
  description: "Generated by AwwalDevs",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={`${quantico.variable} ${poppins.variable}`}>
      <body>
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}